<?php

namespace Blog\ModelBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Blog\ModelBundle\Entity\Author;
use Doctrine\ORM\EntityRepository;

/**
 * Class AuthorRepository
 */
class AuthorRepository extends EntityRepository
{
     /**
     * find first Author from query
     * @return Author
     */
    public function findFirst()
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('a.id','asc')
            ->setMaxResults(1);
        return $qb->getQuery()->getSingleResult();
    }

     private function getQueryBuilder()
      {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('ModelBundle:Author')
                 ->createQueryBuilder('a');
        return $qb;
      }
}
